### ISSUE TITLE
its good, but try hosting it somwhere and implemting live gaming.

### ISSUE THREAD

**Issue by Anirudh-techie** [saviomartin/ludo#1]
Hello @saviomartin,
I loved the game but I have some ideas to implement:-
1. build the react app and put it in a node app. host the app in a host.
2. implement WebSockets which can be used as a communication for 2 live players.
3. implement anonymous matching which will check who all are checking for a player right now and then match them.
4. if no player found then it will give a bot.
5. the dice rolling and moving animation is a little bad, make it better.  for rolling, no need for moving the dice all the time, just move it when clicked. for the moving of pieces, instead of moving to a place suddenly, move to the tile one by
eg:- if my piece should go 4 tiles forward, first move 1 tile, then move to other.
6. lastly implement player chatting.

thank you

**Comment by saviomartin** [comment]
Ok, Bro, Will look into it. Thanks for contacting me.👍
